version: '3'
services:
  app:
    build: .
    ports:
      - "1234:1234"
    environment:
      AUTH0_API_CLIENT_SECRET: $AUTH0_API_CLIENT_SECRET
      GIN_MODE: $GIN_MODE
      AUTH0_CLIENT_ID: $AUTH0_CLIENT_ID
      AUTH0_DOMAIN: $AUTH0_DOMAIN
      AUTH0_API_AUDIENCE: $AUTH0_API_AUDIENCE
